// NOTE: this file is auto-generated by Construct
declare namespace InstanceType {
	class Screenshot extends ISpriteInstance {
	}
	class NewGame extends ITextInstance {
	}
	class Mouse extends IInstance {
	}
	class __Escena2fondo1Behaviors<InstType> {
		Desvanecer: IFadeBehaviorInstance<InstType>;
	}
	class Escena2fondo1 extends ISpriteInstance {
		instVars: {
			animationN: number,
			State: string
		};
		behaviors: __Escena2fondo1Behaviors<this>;
	}
	class FondoNegro extends ISpriteInstance {
	}
	class EveryThingsFine extends ITextInstance {
	}
	class __SpriteBehaviors<InstType> {
		Bala: IBulletBehaviorInstance<InstType>;
	}
	class Sprite extends ISpriteInstance {
		behaviors: __SpriteBehaviors<this>;
	}
	class ItFeelsLike extends ITextInstance {
	}

}