// NOTE: this file is auto-generated by Construct
declare class IConstructProjectObjects {
	readonly Screenshot: IObjectType<InstanceType.Screenshot>;
	readonly NewGame: IObjectType<InstanceType.NewGame>;
	readonly Mouse: IMouseObjectType<InstanceType.Mouse>;
	readonly Escena2fondo1: IObjectType<InstanceType.Escena2fondo1>;
	readonly FondoNegro: IObjectType<InstanceType.FondoNegro>;
	readonly EveryThingsFine: IObjectType<InstanceType.EveryThingsFine>;
	readonly Sprite: IObjectType<InstanceType.Sprite>;
	readonly ItFeelsLike: IObjectType<InstanceType.ItFeelsLike>;
}